name: Debug SSH Key and Passphrase
  run: |
    echo "SSH Key: ${{ secrets.VPS_SSH }}"
    echo "SSH Passphrase: ${{ secrets.SSH_PASSPHRASE }}"
    
name: Deploy to VPS
on:
  push:
    branches:
      - dev # Change to your main branch or the branch you want to deploy
-

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.VPS_SSH }} # Use SSH keys instead of passwords
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Navigate to your project directory (change this to your project path)
            cd /overkill/client-sona-app

            # Build the Docker image from your Dockerfile
            docker build -t karas34760/sona-app:latest .

            # Pull the latest Docker image (if needed, replace with your image name)
            docker pull karas34760/sona-app:latest

            # Remove any existing Docker container with the same name
            docker stop sona-app || true
            docker rm sona-app || true

            # Run the Docker container with the updated image
            docker run -d --name sona-app -p 3000:3000 karas34760/sona-app:latest
