name: Deploy to VPS
on:
  push:
    branches:
      - dev # Change to your main branch or the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.VPS_SSH }} # Use SSH keys instead of passwords
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |

            cd overkill/client-sona-app

            git pull
            echo "overkill" > /root/.ssh/id_rsa
            echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            docker build -t karas34760/karas-app:latest -f Dockerfile .
            docker push karas34760/karas-app:latest


            docker stop karas-app || true
            docker rm karas-app || true

            # Run the Docker container with the updated image
            docker run -d --name karas-app -p 3000:3000 karas34760/karas-app:latest
